#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_PATH = resolve(ROOT, "config/archimate/archimate-sapd-notation-registry.v1.json");
const OUTPUT_PATH = resolve(ROOT, "frontend/capability-browser/generated/archimateNotationRegistry.generated.js");

const FRONTEND_NOTATION_SOURCES = [
  { key: "actor", sapdElementTypeId: "sapd:information_person", renderer: "actor" },
  { key: "location", sapdElementTypeId: "sapd:information_location", cornerIcon: "location" },
  { key: "grouping", sapdElementTypeId: "sapd:information_grouping", cornerIcon: "grouping", dashed: true },
  { key: "node", sapdElementTypeId: "sapd:information_node", cornerIcon: "node" },
  { key: "device", sapdElementTypeId: "sapd:information_device", cornerIcon: "device" },
  { key: "system-software", sapdElementTypeId: "sapd:information_system_software", cornerIcon: "system-software" },
  { key: "network", sapdElementTypeId: "sapd:information_network", cornerIcon: "network" },
  { key: "facility", sapdElementTypeId: "sapd:information_facility", cornerIcon: "facility" },
  { key: "component", sapdElementTypeId: "sapd:application_component", cornerIcon: "component" },
  { key: "function", sapdElementTypeId: "sapd:application_function", cornerIcon: "function" },
  { key: "service", sapdElementTypeId: "sapd:application_service", cornerIcon: "service" },
  { key: "data", sapdElementTypeId: "sapd:data_object", cornerIcon: "data" },
  { key: "artifact", sapdElementTypeId: "sapd:security_technical_artifact", cornerIcon: "artifact" },
  { key: "event", sapdElementTypeId: "sapd:security_threat", cornerIcon: "event" },
  { key: "business-actor", sapdElementTypeId: "sapd:security_org_unit", cornerIcon: "business-actor" },
  { key: "role", sapdElementTypeId: "sapd:security_work_function", cornerIcon: "role" },
  { key: "process", sapdElementTypeId: "sapd:security_process_l1", cornerIcon: "process" },
];

function readRegistry(path = SOURCE_PATH) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function frontendArchimateId(archimateElementTypeId = "") {
  return archimateElementTypeId.replace(/^archimate:/, "").replaceAll("_", "-");
}

function buildEntry(source, notationBySapdElementTypeId, elementById) {
  const notation = notationBySapdElementTypeId.get(source.sapdElementTypeId);
  const element = elementById.get(source.sapdElementTypeId);
  if (!notation) throw new Error(`Missing notation for ${source.sapdElementTypeId}`);
  if (!element) throw new Error(`Missing SAPD element type for ${source.sapdElementTypeId}`);

  const entry = {
    archimateElementTypeId: frontendArchimateId(element.archimate_element_type_id),
    sapdElementTypeId: element.id,
    sapdSubtype: element.sapd_subtype || null,
    sapdSubtypes: element.sapd_subtypes || null,
    drawioShape: notation.drawio_shape,
    appType: notation.drawio_appType || null,
    archiType: notation.drawio_archiType || null,
    cornerIcon: source.cornerIcon || null,
    renderer: source.renderer || null,
    rounded: notation.drawio_archiType === "rounded",
    dashed: Boolean(source.dashed || notation.style?.dashed),
    drawioSize: [notation.drawio_size?.width, notation.drawio_size?.height].filter((value) => Number.isFinite(Number(value))),
    sourceCellId: notation.source_cell_id,
  };

  return Object.fromEntries(Object.entries(entry).filter(([, value]) => value != null && (!Array.isArray(value) || value.length)));
}

export function buildFrontendRegistry(sourcePath = SOURCE_PATH) {
  const sourceRegistry = readRegistry(sourcePath);
  const notationBySapdElementTypeId = new Map(sourceRegistry.notation_entries.map((entry) => [entry.sapd_element_type_id, entry]));
  const elementById = new Map(sourceRegistry.sapd_element_types.map((entry) => [entry.id, entry]));
  return Object.fromEntries(
    FRONTEND_NOTATION_SOURCES.map((source) => [
      source.key,
      buildEntry(source, notationBySapdElementTypeId, elementById),
    ]),
  );
}

export function renderGeneratedRegistry(registry) {
  return `// Generated by scripts/generate_frontend_archimate_registry.mjs. Do not edit by hand.
(function () {
  window.sapdArchimateNotationRegistry = Object.freeze(${JSON.stringify(registry, null, 2)});
})();
`;
}

export function writeFrontendRegistry(outputPath = OUTPUT_PATH, sourcePath = SOURCE_PATH) {
  const registry = buildFrontendRegistry(sourcePath);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderGeneratedRegistry(registry));
  return { outputPath, count: Object.keys(registry).length };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = writeFrontendRegistry();
  console.log(JSON.stringify({ result: "pass", ...result }, null, 2));
}
